# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7d07ccad687482f027eb0c76bb3e93f8871677a523758a9812a51f941741124b4d528f0c73e97cb905bc2ea4bd2dcd62e918edf95d26d1c8af18fb4985462a

test:
  secret_key_base: f9ba6c7fec6ed2c047acb094ad20a54d4a6469d90f42dd94ab5e1e9cb79d24c033283b480b846a93395b006ecd6791461c3b1327f1a94bb3f25050bfc651ef27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
